spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://129.211.31.178:3308/sell?characterEncoding=utf-8&useSSL=false
  http:
    encoding:
      charset: UTF-8
      force: true
server:
  port: 8090

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cest.entity